In [ ]:
##numpy array and basic

In [7]:
import numpy as np

###creating array from list


In [8]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


###list vs numpy


py_list

In [11]:
pylist=[1,2,3]
print("list multiplication",pylist*2)
np_array=np.array([1,2,3])
print("array is",np_array*2)

list multiplication [1, 2, 3, 1, 2, 3]
array is [2 4 6]


In [16]:
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("list opertion time",time.time()-start)
start=time.time()
np_arr=np.arange(1000000)*2
print("array opertion time",time.time()-start)

list opertion time 0.07901144027709961
array opertion time 0.009194612503051758


###creating array from scratch


In [22]:
zeros=np.zeros((3,4))
print("zeros array",zeros)
ones=np.ones((2,3))
print("one array",ones)
full=np.full((3,4),6)
print("FULL MATRICS IS",full)
rendom=np.random.random((2,3))
print("rendom array",rendom)
sequence=np.arange(0,10,2)
print("sequence array",sequence)

zeros array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array [[1. 1. 1.]
 [1. 1. 1.]]
FULL MATRICS IS [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
rendom array [[0.34962986 0.35639701 0.86018766]
 [0.33716118 0.64359154 0.30040465]]
sequence array [0 2 4 6 8]


###vector, matrics tensor


In [30]:
vector=np.array([1,2,3])
print("vector:",vector)
matrix=np.array([[1,2,3],[4,5,6]])
print("matrics \n",matrix)
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor\n", tensor)

vector: [1 2 3]
matrics 
 [[1 2 3]
 [4 5 6]]
tensor
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###array properties


In [34]:
arr=np.array([[1,2,3],[2,5,6]])
print("shape",arr.shape)
print("dimmension",arr.ndim)
print("size",arr.size)
print("datatype",arr.dtype)

shape (2, 3)
dimmension 2
size 6
datatype int64


###array reshaping

In [37]:
arr=np.arange(10)
print("original array",arr)
reshape=arr.reshape((5,2))
print("reshaped array",reshape)
flatened=arr.flatten()
print("flatten array:",flatened)
##only view change not copy
raveled=reshape.ravel()
print("raveled array:",raveled)


original array [0 1 2 3 4 5 6 7 8 9]
reshaped array [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
flatten array: [0 1 2 3 4 5 6 7 8 9]
raveled array: [0 1 2 3 4 5 6 7 8 9]


transpose


In [39]:
transpose=reshape.T
print("transpose is : ",transpose)

transpose is :  [[0 2 4 6 8]
 [1 3 5 7 9]]
