## numpy array operations

In [7]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("basic slicing",arr[2:7])
print("with step",arr[1:8:2])


basic slicing [3 4 5 6 7]
with step [2 4 6 8]


###for 2d array

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element:",arr2d[1,2])
print("entire row:",arr2d[1])
print("entire row wise",arr2d[:,1])

specific element: 6
entire row: [4 5 6]
entire column: [2 5 8]


## sorting

In [15]:
unsorted=np.array([3,1,4,1,5,9,2,6])
print("sorted array:",np.sort(unsorted))
arr_2d=np.array([[3,1],[1,2],[2,4]])
print("sorted 2d array by coloumns",np.sort(arr_2d,axis=1))
print("array sort",np.sort(arr_2d,axis=0))

sorted array: [1 1 2 3 4 5 6 9]
sorted 2d array by coloumns [[1 3]
 [1 2]
 [2 4]]
array sort [[1 1]
 [2 2]
 [3 4]]


## filter

In [16]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_num=numbers[numbers%2==0]
print("even num",even_num)

even num [ 2  4  6  8 10]


## filter with mask

In [17]:
##mask t pura expressin evaluation r karone store hoi asa
mask=numbers>5
print("numbers greater then 5 ",numbers[mask])


numbers greater then 5  [ 6  7  8  9 10]


## fancy indexing and np.where()

In [ ]:
indices=[0,2,4] #atu alp saba lgbo
print(numbers[indices])
whereres=np.where(numbers>5)
print(whereres) #store indexes of where reasult
print("np where",numbers[whereres])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


In [ ]:
codnarr=np.where(numbers>5,numbers*4,numbers)
print(codnarr)
#this line means if (num>5){num*4} else{num}


[ 1  2  3  4  5 24 28 32 36 40]


## adding and removing data

In [21]:
arr1=np.array([1,2,5,3,4])
arr2=np.array([1,6,5,3,8])
combined=arr1+arr2 # aisa nhi krna ha same index r value bilk add hbo
print(combined)
combinedarr=np.concatenate((arr1,arr2))
print(combinedarr)
arr=np.array([[1,2,3],[4,5,6]])
dele=np.delete(arr,1,axis=0) #row
dele2=np.delete(arr,1,axis=1) #colon
print(dele)
print(dele2)



[ 2  8 10  6 12]
[1 2 5 3 4 1 6 5 3 8]
[[1 2 3]]
[[1 3]
 [4 6]]


### array competibility

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,10,9])
print("array compatibility :",a.shape==c.shape)



array compatibility : False


### addition of new row in 2d array

In [27]:
original=np.array([[1,2],[3,4]])
neew=np.array([[5,6]])
with_new_row=np.vstack((original,neew))
print(original)
print(with_new_row)
newcol=np.array([[2],[4]])
with_new_col=np.hstack((original,newcol))
print("array with new column: ",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
array with new column:  [[1 2 2]
 [3 4 4]]


## delete operation

In [ ]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)
print(deleted)#3 tu nho hbo

[1 2 4 5 6]
