In [5]:
from sklearn import svm,datasets
iris=datasets.load_iris()

In [6]:
import pandas as pd  
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['flower']=iris.target
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [8]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)     flower
0                  5.1               3.5  ...               0.2     setosa
1                  4.9               3.0  ...               0.2     setosa
2                  4.7               3.2  ...               0.2     setosa
3                  4.6               3.1  ...               0.2     setosa
4                  5.0               3.6  ...               0.2     setosa
..                 ...               ...  ...               ...        ...
145                6.7               3.0  ...               2.3  virginica
146                6.3               2.5  ...               1.9  virginica
147                6.5               3.0  ...               2.0  virginica
148                6.2               3.4  ...               2.3  virginica
149                5.9               3.0  ...               1.8  virginica

[150 rows x 5 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,train_size=0.2)

In [10]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)
# the score of model vary every time as our Split of trai and test are rendom


0.9416666666666667

In [11]:
# so we will k fold validation 
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [12]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [13]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

there are many values of c hoew many times you writethe same code

In [14]:
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score
import numpy as np

# Load data
iris = datasets.load_iris()

# Parameters
kernels = ['rbf', 'linear']
c_values = [1, 10, 20]
avg_score = {}

# Loop through combinations
#Combines the kernel and C into a key string like 'rbf_10'.

# Calculates the average score and stores it in the avg_score dictionary.
for kval in kernels:
    for cval in c_values:
        cv_score = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_score)

# Print scores
print(avg_score)


{'rbf_1': np.float64(0.9800000000000001), 'rbf_10': np.float64(0.9800000000000001), 'rbf_20': np.float64(0.9666666666666668), 'linear_1': np.float64(0.9800000000000001), 'linear_10': np.float64(0.9733333333333334), 'linear_20': np.float64(0.9666666666666666)}


In [15]:
# loops are also not convinient
# beacuse the we have to do too many iteration
# sklearn provide an api called grid search cv
# which will do the exact same thing 


In [16]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
  'C':[1,10,20],
  'kernel':['rbf','linear']
},cv=5,return_train_score=False) #last perameterwe write method return s some unwanted perameter

In [17]:
clf.fit(iris.data, iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [18]:
clf.cv_results_

{'mean_fit_time': array([0.00183544, 0.00133085, 0.00165892, 0.00139265, 0.00147715,
        0.00146408]),
 'std_fit_time': array([0.00047041, 0.00014572, 0.00032809, 0.00031263, 0.00029029,
        0.00046609]),
 'mean_score_time': array([0.00139389, 0.00109091, 0.00116482, 0.00110478, 0.00121498,
        0.00108461]),
 'std_score_time': array([0.00026862, 0.00011364, 0.00019344, 0.00017406, 0.00027929,
        0.00028356]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_s

we can store this cv reasults in a df in pandas

In [19]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001835      0.000470  ...        0.016330                1
1       0.001331      0.000146  ...        0.016330                1
2       0.001659      0.000328  ...        0.016330                1
3       0.001393      0.000313  ...        0.038873                4
4       0.001477      0.000290  ...        0.036515                5
5       0.001464      0.000466  ...        0.042164                6

[6 rows x 15 columns]

In [20]:
df[['param_C', 'param_kernel', 'mean_test_score']] # we don't need the other columns

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [21]:
clf.best_score_

np.float64(0.9800000000000001)

In [22]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

if we want to check the scores for a range of perameter then my computational cost goes very high

to tackle this kind of priobklem  sklearn introduce a concept called rendomised cv


In [23]:
# it will not try every permutation and combinationa of perameter it will try rendom combination of this perameter
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C': [1, 10, 20],
    'kernel': ['rbf', 'linear']
},
cv=5, return_train_score=False,
n_iter=2 # we can chose how many perameter you want to do
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1       10       linear         0.973333

choosing best model

In [24]:
from sklearn import svm 
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [25]:
modelperms = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10]
        }
    }
}

In [26]:
from sklearn.model_selection import GridSearchCV

score = []
for model_name, mp in modelperms.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    score.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_peram': clf.best_params_
    })

c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was 

In [28]:
df = pd.DataFrame(score, columns=['model', 'best_score', 'best_peram'])
df

model  best_score                 best_peram
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}