In [76]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [77]:
digits=load_digits()

In [78]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [79]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [80]:
lr.score(X_test,y_test)

0.9685185185185186

In [81]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [82]:
rf=RandomForestClassifier(n_estimators=30)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

after every reexecution the x_train x_test y_train y_test got change every time score chage every time as we reexecute the train test split

In [83]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3) # here we can specify how many many folds we needed
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [84]:
# how can you apply k fold on your dataset
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
	print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [85]:
# to simplify the things we write a method
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)



In [86]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [87]:
scores_1 = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    scores_1.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

In [88]:
scores_rf

[0.9148580968280468, 0.9398998330550918, 0.9081803005008348]

In [89]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [90]:
scores_1

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [91]:
#we have to take average in all three array and select which is best method for the given problem

In [92]:
#we dont have to  this musch code for k fold

In [94]:
# we can use cross val method 
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\dibya\Music\ml\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

array([0.92153589, 0.94156928, 0.91652755])

In [95]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=3)

array([0.88480801, 0.9081803 , 0.89148581])

In [96]:
cross_val_score(RandomForestClassifier(n_estimators=20),digits.data,digits.target,cv=3)

array([0.90984975, 0.93656093, 0.90651085])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3) #tuning the perameter n estimator and tryingb to get which perameter will give best reasult

array([0.93155259, 0.94657763, 0.93155259])

In [98]:
#cross val score is very useful it not only allows you you to compare different algorithm but same algo with different perameter 